language: objective-c

osx_image: xcode11 # 10.14

branches:
  only:
    - master

before_install:
  - gem install cocoapods
  - gem install xcpretty
  - pod update

script:
  - echo "123456789" > Keys/GoogleAPI.key
  - echo "const char *gak = \"MTIzNDU2Nzg5CgoK\";" > Keys/Keys.c
  - ./build.sh

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
