language: objective-c

osx_image: xcode11 # 10.14


branches:
  only:
    - master

before_install:
  - gem install cocoapods
  - gem install xcpretty
  - pod update

script:
  - ./build.sh

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
