language: objective-c

osx_image: xcode11 # 10.14

branches:
  only:
    - master

before_install:
  - gem install xcpretty # Required by build script
  - gem install cocoapods # Dependency management
  - pod update # Install dependencies

script:
  # Create dummy API key
  - echo "123456789" > Keys/GoogleAPI.key
  - echo "const char *gak = \"MTIzNDU2Nzg5CgoK\";" > Keys/Keys.c
  # Run build script
  - ./build.sh

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
