language: objective-c

osx_image: xcode10.2 # 10.14

branches:
  only:
    - master

before_install:
  - gem install cocoapods
  - gem update cocoapods --pre
  - pod update

script:
  - make

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z