language: objective-c

osx_image: xcode10.2 # 10.14

branches:
  only:
    - master

before_install:
  - gem install cocoapods
  - gem install xcpretty
  - pod update
  - touch Embla/Keys/GoogleAPI.key

script:
  - ./build.sh

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
