// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/status.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RPCStatusRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface RPCStatusRoot : GPBRootObject
@end

#pragma mark - RPCStatus

typedef GPB_ENUM(RPCStatus_FieldNumber) {
  RPCStatus_FieldNumber_Code = 1,
  RPCStatus_FieldNumber_Message = 2,
  RPCStatus_FieldNumber_DetailsArray = 3,
};

/**
 * The `Status` type defines a logical error model that is suitable for
 * different programming environments, including REST APIs and RPC APIs. It is
 * used by [gRPC](https://github.com/grpc). Each `Status` message contains
 * three pieces of data: error code, error message, and error details.
 *
 * You can find out more about this error model and how to work with it in the
 * [API Design Guide](https://cloud.google.com/apis/design/errors).
 **/
GPB_FINAL @interface RPCStatus : GPBMessage

/** The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code]. */
@property(nonatomic, readwrite) int32_t code;

/**
 * A developer-facing error message, which should be in English. Any
 * user-facing error message should be localized and sent in the
 * [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/**
 * A list of messages that carry the error details.  There is a common set of
 * message types for APIs to use.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *detailsArray;
/** The number of items in @c detailsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger detailsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
