// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lr/transcript/v1alpha1/transcript.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AlignmentJob;
@class GAPIHttpBody;
@class GPBDuration;
@class GPBTimestamp;
@class RPCStatus;
@class SpeakerInfo;
@class Transcript;
@class TranscriptJob;
@class TranscriptMetadata;
@class Transcript_TranscriptSegment;
@class Transcript_TranscriptSegment_WordInfo;
@class Transcript_Version;
@class TranscriptsOrdering;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ExportFormat

typedef GPB_ENUM(ExportFormat) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ExportFormat_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ExportFormat_ExportFormatUnspecified = 0,

  /**
   * Paint-on style VTT format.
   *
   * Each frame adds a single word and rolls lines up once full. This format
   * is a somewhat hacky way getting paint-on to work with players with VTT
   * support.
   **/
  ExportFormat_VttPaintOn = 2,

  /** Pop-on style VTT format. */
  ExportFormat_VttPopOn = 3,

  /**
   * SRT format
   *
   * This is almost the as VTT_POP_ON
   **/
  ExportFormat_Srt = 4,

  /**
   * Audacity label file
   *
   * This has the start and end time for each word (block) in the transcript. E.g.:
   *
   *     2.150000	2.150000	word1
   *     3.400000	6.100000	word2
   **/
  ExportFormat_AudacityLabels = 5,
};

GPBEnumDescriptor *ExportFormat_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ExportFormat_IsValidValue(int32_t value);

#pragma mark - Enum TranscriptJob_State

typedef GPB_ENUM(TranscriptJob_State) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  TranscriptJob_State_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  TranscriptJob_State_Submitted = 0,

  /**
   * Service is waiting for content to be uploaded using the
   * google.bytestream.ByteStream API
   **/
  TranscriptJob_State_WaitingForContent = 1,

  /** Audio or video is being processed/transcribed. */
  TranscriptJob_State_Processing = 2,

  /**
   * Job finished successfully. Client can use the name `transcript` to call
   * `GetTranscript()`
   **/
  TranscriptJob_State_Success = 3,

  /** Job failed for some reason. */
  TranscriptJob_State_Error = 4,

  /** Job was cancelled by the user */
  TranscriptJob_State_Cancelled = 5,
};

GPBEnumDescriptor *TranscriptJob_State_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TranscriptJob_State_IsValidValue(int32_t value);

#pragma mark - Enum TranscriptMetadata_FileType

typedef GPB_ENUM(TranscriptMetadata_FileType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  TranscriptMetadata_FileType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Not specified. Will return INVALID_ARGUMENT. */
  TranscriptMetadata_FileType_TypeUnspecified = 0,
  TranscriptMetadata_FileType_Audio = 1,
  TranscriptMetadata_FileType_Video = 2,
};

GPBEnumDescriptor *TranscriptMetadata_FileType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TranscriptMetadata_FileType_IsValidValue(int32_t value);

#pragma mark - Enum TranscriptsOrdering_Direction

typedef GPB_ENUM(TranscriptsOrdering_Direction) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  TranscriptsOrdering_Direction_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  TranscriptsOrdering_Direction_DirectionUnspecified = 0,
  TranscriptsOrdering_Direction_Descending = 1,
  TranscriptsOrdering_Direction_Ascending = 2,
};

GPBEnumDescriptor *TranscriptsOrdering_Direction_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TranscriptsOrdering_Direction_IsValidValue(int32_t value);

#pragma mark - Enum AlignmentJob_State

typedef GPB_ENUM(AlignmentJob_State) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AlignmentJob_State_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AlignmentJob_State_StateUnspecified = 0,

  /** AlignmentJob has been submitted. */
  AlignmentJob_State_Submitted = 1,

  /** Job is waiting in the queue */
  AlignmentJob_State_Queued = 2,

  /** Transcoding media for processing */
  AlignmentJob_State_Transcoding = 3,

  /** Media is being aligned */
  AlignmentJob_State_Aligning = 4,

  /**
   * Job finished successfully.
   *
   * The Transcript has been updated with the new alignment.
   **/
  AlignmentJob_State_Success = 5,

  /** Job failed for some reason. See the `error` field for details. */
  AlignmentJob_State_Error = 6,

  /** Job was cancelled by the user */
  AlignmentJob_State_Cancelled = 7,
};

GPBEnumDescriptor *AlignmentJob_State_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AlignmentJob_State_IsValidValue(int32_t value);

#pragma mark - Enum SpeakerInfo_AgeGroup

typedef GPB_ENUM(SpeakerInfo_AgeGroup) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SpeakerInfo_AgeGroup_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SpeakerInfo_AgeGroup_AgeGroupUnspecified = 0,

  /** Ages [0;13[ */
  SpeakerInfo_AgeGroup_Child = 1,

  /** Ages [13-18[ */
  SpeakerInfo_AgeGroup_Teenager = 2,

  /** Ages [18;65[ */
  SpeakerInfo_AgeGroup_Adult = 3,

  /** [65; inf[ */
  SpeakerInfo_AgeGroup_Pensioner = 4,
};

GPBEnumDescriptor *SpeakerInfo_AgeGroup_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SpeakerInfo_AgeGroup_IsValidValue(int32_t value);

#pragma mark - Enum SpeakerInfo_Gender

typedef GPB_ENUM(SpeakerInfo_Gender) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SpeakerInfo_Gender_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SpeakerInfo_Gender_GenderUnspecified = 0,
  SpeakerInfo_Gender_Male = 1,
  SpeakerInfo_Gender_Female = 2,
  SpeakerInfo_Gender_Other = 3,
};

GPBEnumDescriptor *SpeakerInfo_Gender_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SpeakerInfo_Gender_IsValidValue(int32_t value);

#pragma mark - TranscriptRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TranscriptRoot : GPBRootObject
@end

#pragma mark - CreateTranscriptRequest

typedef GPB_ENUM(CreateTranscriptRequest_FieldNumber) {
  CreateTranscriptRequest_FieldNumber_Transcript = 1,
};

GPB_FINAL @interface CreateTranscriptRequest : GPBMessage

/** Any non output-only field can be set */
@property(nonatomic, readwrite, strong, null_resettable) Transcript *transcript;
/** Test to see if @c transcript has been set. */
@property(nonatomic, readwrite) BOOL hasTranscript;

@end

#pragma mark - CreateTranscriptResponse

typedef GPB_ENUM(CreateTranscriptResponse_FieldNumber) {
  CreateTranscriptResponse_FieldNumber_Name = 1,
};

GPB_FINAL @interface CreateTranscriptResponse : GPBMessage

/**
 * Resouce identifier for the created transcript:
 * `transcripts/{some-unique-name}`
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - UpdateTranscriptRequest

typedef GPB_ENUM(UpdateTranscriptRequest_FieldNumber) {
  UpdateTranscriptRequest_FieldNumber_Transcript = 1,
};

GPB_FINAL @interface UpdateTranscriptRequest : GPBMessage

/** Any non output-only field that is set will be updated */
@property(nonatomic, readwrite, strong, null_resettable) Transcript *transcript;
/** Test to see if @c transcript has been set. */
@property(nonatomic, readwrite) BOOL hasTranscript;

@end

#pragma mark - DeleteTranscriptRequest

typedef GPB_ENUM(DeleteTranscriptRequest_FieldNumber) {
  DeleteTranscriptRequest_FieldNumber_Name = 1,
};

GPB_FINAL @interface DeleteTranscriptRequest : GPBMessage

/** Any non output-only field that is set will be deleted */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - WatchTranscriptJobsRequest

typedef GPB_ENUM(WatchTranscriptJobsRequest_FieldNumber) {
  WatchTranscriptJobsRequest_FieldNumber_Filter = 1,
};

GPB_FINAL @interface WatchTranscriptJobsRequest : GPBMessage

/** Not implemented */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@end

#pragma mark - WatchTranscriptJobsResponse

typedef GPB_ENUM(WatchTranscriptJobsResponse_FieldNumber) {
  WatchTranscriptJobsResponse_FieldNumber_Update = 1,
  WatchTranscriptJobsResponse_FieldNumber_JobsArray = 2,
};

GPB_FINAL @interface WatchTranscriptJobsResponse : GPBMessage

/** When `update` == `true` the `jobs` will only contain updates. */
@property(nonatomic, readwrite) BOOL update;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TranscriptJob*> *jobsArray;
/** The number of items in @c jobsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger jobsArray_Count;

@end

#pragma mark - TranscriptJob

typedef GPB_ENUM(TranscriptJob_FieldNumber) {
  TranscriptJob_FieldNumber_Name = 1,
  TranscriptJob_FieldNumber_State = 2,
  TranscriptJob_FieldNumber_ProgressPercent = 3,
  TranscriptJob_FieldNumber_StartTime = 4,
  TranscriptJob_FieldNumber_LastUpdatedTime = 5,
  TranscriptJob_FieldNumber_Transcript = 6,
  TranscriptJob_FieldNumber_Error = 7,
  TranscriptJob_FieldNumber_TranscriptMetadata = 8,
};

typedef GPB_ENUM(TranscriptJob_Result_OneOfCase) {
  TranscriptJob_Result_OneOfCase_GPBUnsetOneOfCase = 0,
  TranscriptJob_Result_OneOfCase_Transcript = 6,
  TranscriptJob_Result_OneOfCase_Error = 7,
};

GPB_FINAL @interface TranscriptJob : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** State of the transcription job for `transcript` */
@property(nonatomic, readwrite) TranscriptJob_State state;

@property(nonatomic, readwrite) int32_t progressPercent;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *startTime;
/** Test to see if @c startTime has been set. */
@property(nonatomic, readwrite) BOOL hasStartTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *lastUpdatedTime;
/** Test to see if @c lastUpdatedTime has been set. */
@property(nonatomic, readwrite) BOOL hasLastUpdatedTime;

@property(nonatomic, readonly) TranscriptJob_Result_OneOfCase resultOneOfCase;

/** Name of the transcript. Only set if `state` == `State.SUCCESS`. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transcript;

@property(nonatomic, readwrite, strong, null_resettable) RPCStatus *error;

@property(nonatomic, readwrite, strong, null_resettable) TranscriptMetadata *transcriptMetadata;
/** Test to see if @c transcriptMetadata has been set. */
@property(nonatomic, readwrite) BOOL hasTranscriptMetadata;

@end

/**
 * Fetches the raw value of a @c TranscriptJob's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TranscriptJob_State_RawValue(TranscriptJob *message);
/**
 * Sets the raw value of an @c TranscriptJob's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTranscriptJob_State_RawValue(TranscriptJob *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'result'.
 **/
void TranscriptJob_ClearResultOneOfCase(TranscriptJob *message);

#pragma mark - TranscriptMetadata

typedef GPB_ENUM(TranscriptMetadata_FieldNumber) {
  TranscriptMetadata_FieldNumber_FileType = 1,
  TranscriptMetadata_FieldNumber_LanguageCode = 2,
  TranscriptMetadata_FieldNumber_OriginalFilename = 3,
  TranscriptMetadata_FieldNumber_OriginalUri = 4,
  TranscriptMetadata_FieldNumber_Subject = 5,
  TranscriptMetadata_FieldNumber_Description_p = 6,
  TranscriptMetadata_FieldNumber_KeywordsArray = 7,
  TranscriptMetadata_FieldNumber_AdditionalMetadata = 8,
  TranscriptMetadata_FieldNumber_RecordingDuration = 9,
  TranscriptMetadata_FieldNumber_Dictation = 10,
  TranscriptMetadata_FieldNumber_Speakers = 11,
  TranscriptMetadata_FieldNumber_WaveformUri = 12,
};

typedef GPB_ENUM(TranscriptMetadata_OriginalSource_OneOfCase) {
  TranscriptMetadata_OriginalSource_OneOfCase_GPBUnsetOneOfCase = 0,
  TranscriptMetadata_OriginalSource_OneOfCase_OriginalFilename = 3,
  TranscriptMetadata_OriginalSource_OneOfCase_OriginalUri = 4,
  TranscriptMetadata_OriginalSource_OneOfCase_Dictation = 10,
};

GPB_FINAL @interface TranscriptMetadata : GPBMessage

/**
 * *Required* The format of the original file, i.e. whether it's audio or
 * video.
 **/
@property(nonatomic, readwrite) TranscriptMetadata_FileType fileType;

/**
 * *Required* The language of the supplied audio as a
 * [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag.
 * Example: "en-US".
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *languageCode;

@property(nonatomic, readonly) TranscriptMetadata_OriginalSource_OneOfCase originalSourceOneOfCase;

/** *Output-only* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *originalFilename;

/**
 * *Output-only* This will not be set if original submission used file content
 * instead of URI.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *originalUri;

@property(nonatomic, readwrite) BOOL dictation;

/** The subject, or title, of the transcript. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

/** A free-form description of the contents of the transcript. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/** A collection of server or user generated keywords for the transcript. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keywordsArray;
/** The number of items in @c keywordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keywordsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *additionalMetadata;
/** The number of items in @c additionalMetadata without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger additionalMetadata_Count;

/** *Output-only* The total duration of the recording. */
@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *recordingDuration;
/** Test to see if @c recordingDuration has been set. */
@property(nonatomic, readwrite) BOOL hasRecordingDuration;

/**
 * *Output-only* The URI of a file containing waveform data peaks compatible
 * *with e.g. Wavesurfer.js
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *waveformUri;

/**
 * A mapping from the speaker_id to speaker info for all speakers appearing in
 * the transcript.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, SpeakerInfo*> *speakers;
/** The number of items in @c speakers without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger speakers_Count;

@end

/**
 * Fetches the raw value of a @c TranscriptMetadata's @c fileType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TranscriptMetadata_FileType_RawValue(TranscriptMetadata *message);
/**
 * Sets the raw value of an @c TranscriptMetadata's @c fileType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTranscriptMetadata_FileType_RawValue(TranscriptMetadata *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'originalSource'.
 **/
void TranscriptMetadata_ClearOriginalSourceOneOfCase(TranscriptMetadata *message);

#pragma mark - Transcript

typedef GPB_ENUM(Transcript_FieldNumber) {
  Transcript_FieldNumber_Name = 1,
  Transcript_FieldNumber_Metadata = 2,
  Transcript_FieldNumber_SegmentsArray = 3,
  Transcript_FieldNumber_Uri = 4,
  Transcript_FieldNumber_Version = 5,
};

GPB_FINAL @interface Transcript : GPBMessage

/** The server-assigned name. Should have the format of `transcripts/{some-unique-name}`. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) TranscriptMetadata *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

/** A `transcript` consists of multiple audio aligned segments. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transcript_TranscriptSegment*> *segmentsArray;
/** The number of items in @c segmentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger segmentsArray_Count;

/**
 * The URI for locating the audio (or video) for the transcript. This may be
 * an external URI if a URI was orignally submitted.  If submission was done
 * by a file upload this will be a server-generated uri.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** *output-only* */
@property(nonatomic, readwrite, strong, null_resettable) Transcript_Version *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

@end

#pragma mark - Transcript_TranscriptSegment

typedef GPB_ENUM(Transcript_TranscriptSegment_FieldNumber) {
  Transcript_TranscriptSegment_FieldNumber_StartTime = 1,
  Transcript_TranscriptSegment_FieldNumber_EndTime = 2,
  Transcript_TranscriptSegment_FieldNumber_WordsArray = 3,
  Transcript_TranscriptSegment_FieldNumber_SpeakerId = 4,
};

GPB_FINAL @interface Transcript_TranscriptSegment : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *startTime;
/** Test to see if @c startTime has been set. */
@property(nonatomic, readwrite) BOOL hasStartTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *endTime;
/** Test to see if @c endTime has been set. */
@property(nonatomic, readwrite) BOOL hasEndTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transcript_TranscriptSegment_WordInfo*> *wordsArray;
/** The number of items in @c wordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wordsArray_Count;

/** An ID that is unique for the speaker within the transcript. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *speakerId;

@end

#pragma mark - Transcript_TranscriptSegment_WordInfo

typedef GPB_ENUM(Transcript_TranscriptSegment_WordInfo_FieldNumber) {
  Transcript_TranscriptSegment_WordInfo_FieldNumber_StartTime = 1,
  Transcript_TranscriptSegment_WordInfo_FieldNumber_EndTime = 2,
  Transcript_TranscriptSegment_WordInfo_FieldNumber_Word = 3,
};

GPB_FINAL @interface Transcript_TranscriptSegment_WordInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *startTime;
/** Test to see if @c startTime has been set. */
@property(nonatomic, readwrite) BOOL hasStartTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *endTime;
/** Test to see if @c endTime has been set. */
@property(nonatomic, readwrite) BOOL hasEndTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *word;

@end

#pragma mark - Transcript_Version

typedef GPB_ENUM(Transcript_Version_FieldNumber) {
  Transcript_Version_FieldNumber_Name = 1,
  Transcript_Version_FieldNumber_Parent = 2,
  Transcript_Version_FieldNumber_CreationTime = 3,
};

GPB_FINAL @interface Transcript_Version : GPBMessage

/** Server-assigned name of version */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Version name of parent. Unset if there is no parent. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *parent;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *creationTime;
/** Test to see if @c creationTime has been set. */
@property(nonatomic, readwrite) BOOL hasCreationTime;

@end

#pragma mark - SubmitTranscriptJobRequest

typedef GPB_ENUM(SubmitTranscriptJobRequest_FieldNumber) {
  SubmitTranscriptJobRequest_FieldNumber_Metadata = 1,
  SubmitTranscriptJobRequest_FieldNumber_UseUri = 2,
  SubmitTranscriptJobRequest_FieldNumber_Uri = 3,
};

GPB_FINAL @interface SubmitTranscriptJobRequest : GPBMessage

/**
 * At least the following fields of `metadata` are required to be set:
 * `metadata.file_type`, `metadata.language_code`
 **/
@property(nonatomic, readwrite, strong, null_resettable) TranscriptMetadata *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

/**
 * Files can be submitted to be transcribed either by a URI accessible by the
 * service or uploaded using the google.bytestream.ByteStream API using the
 * resource name "blob/{transcript_name}",
 * e.g. "blob/transcripts/42d1b568-fad4-4312-b134-05a8488724bf"
 **/
@property(nonatomic, readwrite) BOOL useUri;

/**
 * Required to be set if `use_uri==true`. A URI, accessible by the service,
 * which points to an audio or video file/stream to be transcribed.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

@end

#pragma mark - GetTranscriptJobRequest

typedef GPB_ENUM(GetTranscriptJobRequest_FieldNumber) {
  GetTranscriptJobRequest_FieldNumber_Name = 1,
};

GPB_FINAL @interface GetTranscriptJobRequest : GPBMessage

/** TranscriptJob name. For example: "transcriptjob/42d1b568-fad4-4312-b134-05a8488724bf" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - GetTranscriptRequest

typedef GPB_ENUM(GetTranscriptRequest_FieldNumber) {
  GetTranscriptRequest_FieldNumber_Name = 1,
  GetTranscriptRequest_FieldNumber_Version = 2,
};

GPB_FINAL @interface GetTranscriptRequest : GPBMessage

/** Resource name of transcript. For example: "transcripts/xyz" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Set to request a specific version of the transcript */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@end

#pragma mark - ListTranscriptJobsRequest

typedef GPB_ENUM(ListTranscriptJobsRequest_FieldNumber) {
  ListTranscriptJobsRequest_FieldNumber_Filter = 1,
  ListTranscriptJobsRequest_FieldNumber_PageSize = 2,
  ListTranscriptJobsRequest_FieldNumber_PageToken = 3,
};

GPB_FINAL @interface ListTranscriptJobsRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@end

#pragma mark - ListTranscriptJobsResponse

typedef GPB_ENUM(ListTranscriptJobsResponse_FieldNumber) {
  ListTranscriptJobsResponse_FieldNumber_JobsArray = 1,
  ListTranscriptJobsResponse_FieldNumber_NextPageToken = 2,
};

GPB_FINAL @interface ListTranscriptJobsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TranscriptJob*> *jobsArray;
/** The number of items in @c jobsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger jobsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - TranscriptsOrdering

typedef GPB_ENUM(TranscriptsOrdering_FieldNumber) {
  TranscriptsOrdering_FieldNumber_Direction = 1,
  TranscriptsOrdering_FieldNumber_OrderBy = 2,
};

GPB_FINAL @interface TranscriptsOrdering : GPBMessage

/**
 * Requested order of returned results.
 *
 * Default is DESCENDING
 **/
@property(nonatomic, readwrite) TranscriptsOrdering_Direction direction;

/**
 * Order returned results by the specified field in `Transcript`
 *
 * The only fields currently supported are `subject`,
 * `metadata.recording_duration`, and `version.creation_time`.
 *
 * If left unspecified results are ordered by `version.creation_time`
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderBy;

@end

/**
 * Fetches the raw value of a @c TranscriptsOrdering's @c direction property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TranscriptsOrdering_Direction_RawValue(TranscriptsOrdering *message);
/**
 * Sets the raw value of an @c TranscriptsOrdering's @c direction property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTranscriptsOrdering_Direction_RawValue(TranscriptsOrdering *message, int32_t value);

#pragma mark - WatchTranscriptsRequest

typedef GPB_ENUM(WatchTranscriptsRequest_FieldNumber) {
  WatchTranscriptsRequest_FieldNumber_Filter = 1,
  WatchTranscriptsRequest_FieldNumber_PageSize = 2,
  WatchTranscriptsRequest_FieldNumber_PageToken = 3,
  WatchTranscriptsRequest_FieldNumber_Ordering = 4,
};

GPB_FINAL @interface WatchTranscriptsRequest : GPBMessage

/** See filter in [ListTranscriptsRequest](#ListTranscriptsRequest) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@property(nonatomic, readwrite, strong, null_resettable) TranscriptsOrdering *ordering;
/** Test to see if @c ordering has been set. */
@property(nonatomic, readwrite) BOOL hasOrdering;

@end

#pragma mark - WatchTranscriptsResponse

typedef GPB_ENUM(WatchTranscriptsResponse_FieldNumber) {
  WatchTranscriptsResponse_FieldNumber_Update = 1,
  WatchTranscriptsResponse_FieldNumber_TranscriptsArray = 2,
  WatchTranscriptsResponse_FieldNumber_NextPageToken = 3,
};

GPB_FINAL @interface WatchTranscriptsResponse : GPBMessage

/** When `update` == `true` the `transcripts` field will only contain updates. */
@property(nonatomic, readwrite) BOOL update;

/** The returned transcripts will not have segments field set. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transcript*> *transcriptsArray;
/** The number of items in @c transcriptsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transcriptsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - ListTranscriptsRequest

typedef GPB_ENUM(ListTranscriptsRequest_FieldNumber) {
  ListTranscriptsRequest_FieldNumber_Filter = 1,
  ListTranscriptsRequest_FieldNumber_PageSize = 2,
  ListTranscriptsRequest_FieldNumber_PageToken = 3,
  ListTranscriptsRequest_FieldNumber_Ordering = 4,
};

GPB_FINAL @interface ListTranscriptsRequest : GPBMessage

/**
 * Lists of Transcripts can be filtered by the following fields
 * of metadata: keywords and subject
 *
 * To retrieve all transcripts which have either keyword1 or keyword1:
 *    metadata.keywords CONTAINS ["keyword1", "keyword2"]
 *
 * To filter by subject:
 *   metadata.subject CONTAINS "this is a subject"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@property(nonatomic, readwrite, strong, null_resettable) TranscriptsOrdering *ordering;
/** Test to see if @c ordering has been set. */
@property(nonatomic, readwrite) BOOL hasOrdering;

@end

#pragma mark - ListTranscriptsResponse

typedef GPB_ENUM(ListTranscriptsResponse_FieldNumber) {
  ListTranscriptsResponse_FieldNumber_TranscriptsArray = 1,
  ListTranscriptsResponse_FieldNumber_NextPageToken = 2,
};

GPB_FINAL @interface ListTranscriptsResponse : GPBMessage

/** The returned transcripts will not have segments field set. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transcript*> *transcriptsArray;
/** The number of items in @c transcriptsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transcriptsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - ExportTranscriptRequest

typedef GPB_ENUM(ExportTranscriptRequest_FieldNumber) {
  ExportTranscriptRequest_FieldNumber_Name = 1,
  ExportTranscriptRequest_FieldNumber_Format = 2,
  ExportTranscriptRequest_FieldNumber_Version = 3,
};

GPB_FINAL @interface ExportTranscriptRequest : GPBMessage

/** Resource name of transcript. For example: "transcripts/xyz". */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Set to request a specific version of the transcript. Defaults to the most
 * recent number.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** Which format to export */
@property(nonatomic, readwrite) ExportFormat format;

@end

/**
 * Fetches the raw value of a @c ExportTranscriptRequest's @c format property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ExportTranscriptRequest_Format_RawValue(ExportTranscriptRequest *message);
/**
 * Sets the raw value of an @c ExportTranscriptRequest's @c format property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetExportTranscriptRequest_Format_RawValue(ExportTranscriptRequest *message, int32_t value);

#pragma mark - ExportTranscriptResponse

typedef GPB_ENUM(ExportTranscriptResponse_FieldNumber) {
  ExportTranscriptResponse_FieldNumber_ExportedTranscript = 1,
};

GPB_FINAL @interface ExportTranscriptResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GAPIHttpBody *exportedTranscript;
/** Test to see if @c exportedTranscript has been set. */
@property(nonatomic, readwrite) BOOL hasExportedTranscript;

@end

#pragma mark - WatchAlignmentJobsRequest

typedef GPB_ENUM(WatchAlignmentJobsRequest_FieldNumber) {
  WatchAlignmentJobsRequest_FieldNumber_Filter = 1,
  WatchAlignmentJobsRequest_FieldNumber_UpdateOnly = 2,
};

GPB_FINAL @interface WatchAlignmentJobsRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

/**
 * Set to true to only watch for updates to jobs.
 *
 * The server will send responses iff jobs receive updates and all responses
 * will have update==true
 **/
@property(nonatomic, readwrite) BOOL updateOnly;

@end

#pragma mark - WatchAlignmentJobsResponse

typedef GPB_ENUM(WatchAlignmentJobsResponse_FieldNumber) {
  WatchAlignmentJobsResponse_FieldNumber_Update = 1,
  WatchAlignmentJobsResponse_FieldNumber_JobsArray = 2,
};

GPB_FINAL @interface WatchAlignmentJobsResponse : GPBMessage

/** When `update` == `true` the `jobs` will only contain updates. */
@property(nonatomic, readwrite) BOOL update;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AlignmentJob*> *jobsArray;
/** The number of items in @c jobsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger jobsArray_Count;

@end

#pragma mark - AlignmentJob

typedef GPB_ENUM(AlignmentJob_FieldNumber) {
  AlignmentJob_FieldNumber_Name = 1,
  AlignmentJob_FieldNumber_State = 2,
  AlignmentJob_FieldNumber_ProgressPercent = 3,
  AlignmentJob_FieldNumber_StartTime = 4,
  AlignmentJob_FieldNumber_LastUpdatedTime = 5,
  AlignmentJob_FieldNumber_Transcript = 6,
  AlignmentJob_FieldNumber_Error = 7,
  AlignmentJob_FieldNumber_TranscriptVersion = 8,
};

GPB_FINAL @interface AlignmentJob : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** State of the alignment job for `transcript`. */
@property(nonatomic, readwrite) AlignmentJob_State state;

@property(nonatomic, readwrite) int32_t progressPercent;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *startTime;
/** Test to see if @c startTime has been set. */
@property(nonatomic, readwrite) BOOL hasStartTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *lastUpdatedTime;
/** Test to see if @c lastUpdatedTime has been set. */
@property(nonatomic, readwrite) BOOL hasLastUpdatedTime;

/** Name of transcript being aligned. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transcript;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transcriptVersion;

/** Error details set if state==ERROR */
@property(nonatomic, readwrite, strong, null_resettable) RPCStatus *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

@end

/**
 * Fetches the raw value of a @c AlignmentJob's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AlignmentJob_State_RawValue(AlignmentJob *message);
/**
 * Sets the raw value of an @c AlignmentJob's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAlignmentJob_State_RawValue(AlignmentJob *message, int32_t value);

#pragma mark - ListAlignmentJobsRequest

typedef GPB_ENUM(ListAlignmentJobsRequest_FieldNumber) {
  ListAlignmentJobsRequest_FieldNumber_Filter = 1,
  ListAlignmentJobsRequest_FieldNumber_PageSize = 2,
  ListAlignmentJobsRequest_FieldNumber_PageToken = 3,
};

GPB_FINAL @interface ListAlignmentJobsRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

@property(nonatomic, readwrite) int32_t pageSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@end

#pragma mark - ListAlignmentJobsResponse

typedef GPB_ENUM(ListAlignmentJobsResponse_FieldNumber) {
  ListAlignmentJobsResponse_FieldNumber_JobsArray = 1,
  ListAlignmentJobsResponse_FieldNumber_NextPageToken = 2,
};

GPB_FINAL @interface ListAlignmentJobsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AlignmentJob*> *jobsArray;
/** The number of items in @c jobsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger jobsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - SubmitAlignmentJobRequest

typedef GPB_ENUM(SubmitAlignmentJobRequest_FieldNumber) {
  SubmitAlignmentJobRequest_FieldNumber_Transcript = 1,
};

GPB_FINAL @interface SubmitAlignmentJobRequest : GPBMessage

/**
 * The name of the transcript to (re-)align.
 *
 * For example: "transcripts/42d1b568-fad4-4312-b134-05a8488724bf"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *transcript;

@end

#pragma mark - GetAlignmentJobRequest

typedef GPB_ENUM(GetAlignmentJobRequest_FieldNumber) {
  GetAlignmentJobRequest_FieldNumber_Name = 1,
  GetAlignmentJobRequest_FieldNumber_Transcript = 2,
};

typedef GPB_ENUM(GetAlignmentJobRequest_Resources_OneOfCase) {
  GetAlignmentJobRequest_Resources_OneOfCase_GPBUnsetOneOfCase = 0,
  GetAlignmentJobRequest_Resources_OneOfCase_Name = 1,
  GetAlignmentJobRequest_Resources_OneOfCase_Transcript = 2,
};

GPB_FINAL @interface GetAlignmentJobRequest : GPBMessage

@property(nonatomic, readonly) GetAlignmentJobRequest_Resources_OneOfCase resourcesOneOfCase;

/**
 * The name of the alignment job to get the status for.
 *
 * For example: "alignmentjobs/42d1b568-fad4-4312-b134-05a8488724bf"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Get the latest alignment job by the name of the target transcript
 *
 * For example: "transcripts/42d1b568-fad4-4312-b134-05a8488724bf"
 * or to align a specific version (other than the most recent):
 *   "transcripts/42d1b568-fad4-4312-b134-05a8488724bf/version/fc694a69-84b6-4c14-9498-bfb93ab68d54"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *transcript;

@end

/**
 * Clears whatever value was set for the oneof 'resources'.
 **/
void GetAlignmentJobRequest_ClearResourcesOneOfCase(GetAlignmentJobRequest *message);

#pragma mark - CancelAlignmentJobRequest

typedef GPB_ENUM(CancelAlignmentJobRequest_FieldNumber) {
  CancelAlignmentJobRequest_FieldNumber_Name = 1,
};

GPB_FINAL @interface CancelAlignmentJobRequest : GPBMessage

/**
 * The name of the alignment job to cancel.
 *
 * For example: "alignmentjobs/42d1b568-fad4-4312-b134-05a8488724bf"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - SpeakerInfo

typedef GPB_ENUM(SpeakerInfo_FieldNumber) {
  SpeakerInfo_FieldNumber_FullName = 1,
  SpeakerInfo_FieldNumber_AgeGroup = 2,
  SpeakerInfo_FieldNumber_Gender = 3,
};

GPB_FINAL @interface SpeakerInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fullName;

@property(nonatomic, readwrite) SpeakerInfo_AgeGroup ageGroup;

@property(nonatomic, readwrite) SpeakerInfo_Gender gender;

@end

/**
 * Fetches the raw value of a @c SpeakerInfo's @c ageGroup property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SpeakerInfo_AgeGroup_RawValue(SpeakerInfo *message);
/**
 * Sets the raw value of an @c SpeakerInfo's @c ageGroup property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSpeakerInfo_AgeGroup_RawValue(SpeakerInfo *message, int32_t value);

/**
 * Fetches the raw value of a @c SpeakerInfo's @c gender property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SpeakerInfo_Gender_RawValue(SpeakerInfo *message);
/**
 * Sets the raw value of an @c SpeakerInfo's @c gender property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSpeakerInfo_Gender_RawValue(SpeakerInfo *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
