// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bytestream/bytestream.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BytestreamRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BytestreamRoot : GPBRootObject
@end

#pragma mark - ReadRequest

typedef GPB_ENUM(ReadRequest_FieldNumber) {
  ReadRequest_FieldNumber_ResourceName = 1,
  ReadRequest_FieldNumber_ReadOffset = 2,
  ReadRequest_FieldNumber_ReadLimit = 3,
};

/**
 * Request object for ByteStream.Read.
 **/
GPB_FINAL @interface ReadRequest : GPBMessage

/** The name of the resource to read. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceName;

/**
 * The offset for the first byte to return in the read, relative to the start
 * of the resource.
 *
 * A `read_offset` that is negative or greater than the size of the resource
 * will cause an `OUT_OF_RANGE` error.
 **/
@property(nonatomic, readwrite) int64_t readOffset;

/**
 * The maximum number of `data` bytes the server is allowed to return in the
 * sum of all `ReadResponse` messages. A `read_limit` of zero indicates that
 * there is no limit, and a negative `read_limit` will cause an error.
 *
 * If the stream returns fewer bytes than allowed by the `read_limit` and no
 * error occurred, the stream includes all data from the `read_offset` to the
 * end of the resource.
 **/
@property(nonatomic, readwrite) int64_t readLimit;

@end

#pragma mark - ReadResponse

typedef GPB_ENUM(ReadResponse_FieldNumber) {
  ReadResponse_FieldNumber_Data_p = 10,
};

/**
 * Response object for ByteStream.Read.
 **/
GPB_FINAL @interface ReadResponse : GPBMessage

/**
 * A portion of the data for the resource. The service **may** leave `data`
 * empty for any given `ReadResponse`. This enables the service to inform the
 * client that the request is still live while it is running an operation to
 * generate more data.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - WriteRequest

typedef GPB_ENUM(WriteRequest_FieldNumber) {
  WriteRequest_FieldNumber_ResourceName = 1,
  WriteRequest_FieldNumber_WriteOffset = 2,
  WriteRequest_FieldNumber_FinishWrite = 3,
  WriteRequest_FieldNumber_Data_p = 10,
};

/**
 * Request object for ByteStream.Write.
 **/
GPB_FINAL @interface WriteRequest : GPBMessage

/**
 * The name of the resource to write. This **must** be set on the first
 * `WriteRequest` of each `Write()` action. If it is set on subsequent calls,
 * it **must** match the value of the first request.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceName;

/**
 * The offset from the beginning of the resource at which the data should be
 * written. It is required on all `WriteRequest`s.
 *
 * In the first `WriteRequest` of a `Write()` action, it indicates
 * the initial offset for the `Write()` call. The value **must** be equal to
 * the `committed_size` that a call to `QueryWriteStatus()` would return.
 *
 * On subsequent calls, this value **must** be set and **must** be equal to
 * the sum of the first `write_offset` and the sizes of all `data` bundles
 * sent previously on this stream.
 *
 * An incorrect value will cause an error.
 **/
@property(nonatomic, readwrite) int64_t writeOffset;

/**
 * If `true`, this indicates that the write is complete. Sending any
 * `WriteRequest`s subsequent to one in which `finish_write` is `true` will
 * cause an error.
 **/
@property(nonatomic, readwrite) BOOL finishWrite;

/**
 * A portion of the data for the resource. The client **may** leave `data`
 * empty for any given `WriteRequest`. This enables the client to inform the
 * service that the request is still live while it is running an operation to
 * generate more data.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

#pragma mark - WriteResponse

typedef GPB_ENUM(WriteResponse_FieldNumber) {
  WriteResponse_FieldNumber_CommittedSize = 1,
};

/**
 * Response object for ByteStream.Write.
 **/
GPB_FINAL @interface WriteResponse : GPBMessage

/** The number of bytes that have been processed for the given resource. */
@property(nonatomic, readwrite) int64_t committedSize;

@end

#pragma mark - QueryWriteStatusRequest

typedef GPB_ENUM(QueryWriteStatusRequest_FieldNumber) {
  QueryWriteStatusRequest_FieldNumber_ResourceName = 1,
};

/**
 * Request object for ByteStream.QueryWriteStatus.
 **/
GPB_FINAL @interface QueryWriteStatusRequest : GPBMessage

/** The name of the resource whose write status is being requested. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceName;

@end

#pragma mark - QueryWriteStatusResponse

typedef GPB_ENUM(QueryWriteStatusResponse_FieldNumber) {
  QueryWriteStatusResponse_FieldNumber_CommittedSize = 1,
  QueryWriteStatusResponse_FieldNumber_Complete = 2,
};

/**
 * Response object for ByteStream.QueryWriteStatus.
 **/
GPB_FINAL @interface QueryWriteStatusResponse : GPBMessage

/** The number of bytes that have been processed for the given resource. */
@property(nonatomic, readwrite) int64_t committedSize;

/**
 * `complete` is `true` only if the client has sent a `WriteRequest` with
 * `finish_write` set to true, and the server has processed that request.
 **/
@property(nonatomic, readwrite) BOOL complete;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
