// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/longrunning/operations.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;
@class GPBDuration;
@class Operation;
@class RPCStatus;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - OperationsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OperationsRoot : GPBRootObject
@end

@interface OperationsRoot (DynamicMethods)
/**
 * Additional information regarding long-running operations.
 * In particular, this specifies the types that are returned from
 * long-running operations.
 *
 * Required for methods that return `google.longrunning.Operation`; invalid
 * otherwise.
 **/
+ (GPBExtensionDescriptor *)operationInfo;
@end

#pragma mark - Operation

typedef GPB_ENUM(Operation_FieldNumber) {
  Operation_FieldNumber_Name = 1,
  Operation_FieldNumber_Metadata = 2,
  Operation_FieldNumber_Done = 3,
  Operation_FieldNumber_Error = 4,
  Operation_FieldNumber_Response = 5,
};

typedef GPB_ENUM(Operation_Result_OneOfCase) {
  Operation_Result_OneOfCase_GPBUnsetOneOfCase = 0,
  Operation_Result_OneOfCase_Error = 4,
  Operation_Result_OneOfCase_Response = 5,
};

/**
 * This resource represents a long-running operation that is the result of a
 * network API call.
 **/
GPB_FINAL @interface Operation : GPBMessage

/**
 * The server-assigned name, which is only unique within the same service that
 * originally returns it. If you use the default HTTP mapping, the
 * `name` should be a resource name ending with `operations/{unique_id}`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * Service-specific metadata associated with the operation.  It typically
 * contains progress information and common metadata such as create time.
 * Some services might not provide such metadata.  Any method that returns a
 * long-running operation should document the metadata type, if any.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *metadata;
/** Test to see if @c metadata has been set. */
@property(nonatomic, readwrite) BOOL hasMetadata;

/**
 * If the value is `false`, it means the operation is still in progress.
 * If `true`, the operation is completed, and either `error` or `response` is
 * available.
 **/
@property(nonatomic, readwrite) BOOL done;

/**
 * The operation result, which can be either an `error` or a valid `response`.
 * If `done` == `false`, neither `error` nor `response` is set.
 * If `done` == `true`, exactly one of `error` or `response` is set.
 **/
@property(nonatomic, readonly) Operation_Result_OneOfCase resultOneOfCase;

/** The error result of the operation in case of failure or cancellation. */
@property(nonatomic, readwrite, strong, null_resettable) RPCStatus *error;

/**
 * The normal response of the operation in case of success.  If the original
 * method returns no data on success, such as `Delete`, the response is
 * `google.protobuf.Empty`.  If the original method is standard
 * `Get`/`Create`/`Update`, the response should be the resource.  For other
 * methods, the response should have the type `XxxResponse`, where `Xxx`
 * is the original method name.  For example, if the original method name
 * is `TakeSnapshot()`, the inferred response type is
 * `TakeSnapshotResponse`.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *response;

@end

/**
 * Clears whatever value was set for the oneof 'result'.
 **/
void Operation_ClearResultOneOfCase(Operation *message);

#pragma mark - GetOperationRequest

typedef GPB_ENUM(GetOperationRequest_FieldNumber) {
  GetOperationRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Operations.GetOperation][google.longrunning.Operations.GetOperation].
 **/
GPB_FINAL @interface GetOperationRequest : GPBMessage

/** The name of the operation resource. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - ListOperationsRequest

typedef GPB_ENUM(ListOperationsRequest_FieldNumber) {
  ListOperationsRequest_FieldNumber_Filter = 1,
  ListOperationsRequest_FieldNumber_PageSize = 2,
  ListOperationsRequest_FieldNumber_PageToken = 3,
  ListOperationsRequest_FieldNumber_Name = 4,
};

/**
 * The request message for [Operations.ListOperations][google.longrunning.Operations.ListOperations].
 **/
GPB_FINAL @interface ListOperationsRequest : GPBMessage

/** The name of the operation's parent resource. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The standard list filter. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filter;

/** The standard list page size. */
@property(nonatomic, readwrite) int32_t pageSize;

/** The standard list page token. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pageToken;

@end

#pragma mark - ListOperationsResponse

typedef GPB_ENUM(ListOperationsResponse_FieldNumber) {
  ListOperationsResponse_FieldNumber_OperationsArray = 1,
  ListOperationsResponse_FieldNumber_NextPageToken = 2,
};

/**
 * The response message for [Operations.ListOperations][google.longrunning.Operations.ListOperations].
 **/
GPB_FINAL @interface ListOperationsResponse : GPBMessage

/** A list of operations that matches the specified filter in the request. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Operation*> *operationsArray;
/** The number of items in @c operationsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger operationsArray_Count;

/** The standard List next-page token. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nextPageToken;

@end

#pragma mark - CancelOperationRequest

typedef GPB_ENUM(CancelOperationRequest_FieldNumber) {
  CancelOperationRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Operations.CancelOperation][google.longrunning.Operations.CancelOperation].
 **/
GPB_FINAL @interface CancelOperationRequest : GPBMessage

/** The name of the operation resource to be cancelled. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - DeleteOperationRequest

typedef GPB_ENUM(DeleteOperationRequest_FieldNumber) {
  DeleteOperationRequest_FieldNumber_Name = 1,
};

/**
 * The request message for [Operations.DeleteOperation][google.longrunning.Operations.DeleteOperation].
 **/
GPB_FINAL @interface DeleteOperationRequest : GPBMessage

/** The name of the operation resource to be deleted. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - WaitOperationRequest

typedef GPB_ENUM(WaitOperationRequest_FieldNumber) {
  WaitOperationRequest_FieldNumber_Name = 1,
  WaitOperationRequest_FieldNumber_Timeout = 2,
};

/**
 * The request message for [Operations.WaitOperation][google.longrunning.Operations.WaitOperation].
 **/
GPB_FINAL @interface WaitOperationRequest : GPBMessage

/** The name of the operation resource to wait on. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The maximum duration to wait before timing out. If left blank, the wait
 * will be at most the time permitted by the underlying HTTP/RPC protocol.
 * If RPC context deadline is also specified, the shorter one will be used.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *timeout;
/** Test to see if @c timeout has been set. */
@property(nonatomic, readwrite) BOOL hasTimeout;

@end

#pragma mark - OperationInfo

typedef GPB_ENUM(OperationInfo_FieldNumber) {
  OperationInfo_FieldNumber_ResponseType = 1,
  OperationInfo_FieldNumber_MetadataType = 2,
};

/**
 * A message representing the message types used by a long-running operation.
 *
 * Example:
 *
 *   rpc LongRunningRecognize(LongRunningRecognizeRequest)
 *       returns (google.longrunning.Operation) {
 *     option (google.longrunning.operation_info) = {
 *       response_type: "LongRunningRecognizeResponse"
 *       metadata_type: "LongRunningRecognizeMetadata"
 *     };
 *   }
 **/
GPB_FINAL @interface OperationInfo : GPBMessage

/**
 * Required. The message name of the primary return type for this
 * long-running operation.
 * This type will be used to deserialize the LRO's response.
 *
 * If the response is in a different package from the rpc, a fully-qualified
 * message name must be used (e.g. `google.protobuf.Struct`).
 *
 * Note: Altering this value constitutes a breaking change.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *responseType;

/**
 * Required. The message name of the metadata type for this long-running
 * operation.
 *
 * If the response is in a different package from the rpc, a fully-qualified
 * message name must be used (e.g. `google.protobuf.Struct`).
 *
 * Note: Altering this value constitutes a breaking change.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *metadataType;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
