# GitHub Actions workflow for testing build
name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build client using build script
    runs-on: macos-latest

    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: gem install cocoapods
      - run: pod update
      - run: gem install xcpretty
      - run: echo "123456789" > Keys/GoogleAPI.key
      - run: echo "const char *gak = \"MTIzNDU2Nzg5CgoK\";" > Keys/Keys.c
      - run: bash build.sh
      - name: Slack notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Testing
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up event if the job fails
