# GitHub Actions workflow for testing build
name: iOS workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build client using build script
    runs-on: macos-latest

    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: gem install cocoapods
      - run: pod update
      - run: gem install xcpretty
      - run: echo "123456789" > Keys/GoogleAPI.key
      - run: echo "const char *gak = \"MTIzNDU2Nzg5CgoK\";" > Keys/Keys.c
      - run: bash build.sh
